CREATE TABLE "users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstName" varchar NOT NULl,
    "lastName" varchar NOT NULL,
    "email" varchar NOT NULL,
    "password" text NOT NULL,
    "isActive" boolean NOT NULL DEFAULT false,
    "created_at" timestamp  with time zone NOT NULL DEFAULT 'now()',
    "updated_at" timestamp  with time zone NOT NULL DEFAULT 'now()'
);
CREATE UNIQUE INDEX ON "users" ("email");