// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, db DBTX, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error)
	GetSession(ctx context.Context, db DBTX, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, db DBTX, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
